[package]

name = "generic-array"
version = "0.4.1"
authors = [ "Bartłomiej Kamiński <fizyk20@gmail.com>" ]
description = "Generic types implementing functionality of arrays"
license = "MIT"
repository = "https://github.com/fizyk20/generic-array.git"
documentation = "http://fizyk20.github.io/generic-array/generic_array/"

[lib]
name = "generic_array"

[dependencies]
typenum = "1.3.1"
nodrop = "0.1.6"
serde = { version = "~0.8", optional = true }

[dev_dependencies]
# this can't yet be made optional, see https://github.com/rust-lang/cargo/issues/1596
serde_json = "~0.8"

[features]
no_std = []
